baseURL = "supercarmarbella.com"
disableLanguages = []
disqusShortname = "SupercarMarbella Rent and Shop"
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = "Supercar Marbella"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [SupercarMarbella.com](https://www.supercarmarbella.com) & developed by [Googleate.es](https://www.googleate.es)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Accueil"
languageCode = "es-Es"
languageName = "Es"
weight = "2"
[[menu.main]]
name = "Brands"
pre = "#"
url = "portfolio"
weight = 3
[[menu.main]]
name = "All cars"
pre = "#"
url = "blog"
weight = 6
[[menu.main]]
name = "contact"
pre = "#"
url = "contact"
weight = 7
[params]
author = "Santiago Llera"
description = "Supercar Marbella Rent and shop"
google_analytics_id = ""
logo = "images/logo.png"
post_share = false
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "36.511813"
map_longitude = "-4.872766"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[params.preloader]
enable = false
preloader = "images/logo.png"
[[params.social]]
icon = "ti-mobile"
link = "Usa: https://wa.me/34663010971"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/supercarmarbella/"
